outplacement/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('par/', include('par.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

par/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.PARDetail.as_view(), name='par-detail'),
    path('skill/<int:pk>/', views.SkillDetail.as_view(), name='skill-detail'),
    path('skills/', views.SkillList.as_view(), name='skills'),
]

par/models.py
# from django.utils import timezone
from django.urls import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Company(models.Model):
    """This model will hold company names"""

    name = models.CharField(max_length=200, verbose_name=_("Company"))

    class Meta:
        verbose_name = _("Company")
        verbose_name_plural = _("Companies")

    def __str__(self):
        return "{}".format(self.name)


class Skill(models.Model):
    """This model will hold available skills"""

    name = models.CharField(max_length=200, verbose_name=_("Skill"))

    class Meta:
        verbose_name = _("Skill")
        verbose_name_plural = _("Skills")

    def get_absolute_url(self):
        return reverse('skill-detail', args=[str(self.id)])

    def __str__(self):
        return "{}".format(self.name)


class PAR(models.Model):
    """This model will wrap all components of the PAR together"""

    name = models.CharField(max_length=200, verbose_name=_("PAR"))
    problem = models.TextField(blank=True, verbose_name=_("Problem"))
    action = models.TextField(blank=True, verbose_name=_("Action"))
    result = models.TextField(blank=True, verbose_name=_("Result"))
    number = models.PositiveSmallIntegerField(default=0,
                                              blank=False,
                                              null=False,
                                              db_index=True)
    skills = models.ManyToManyField(Skill,
                                    blank=True,
                                    verbose_name=_("Skills"))
    company = models.ForeignKey(Company,
                                blank=True,
                                null=True,
                                on_delete=models.SET_NULL,
                                verbose_name=_("Company"))

    class Meta:
        ordering = ['-number']
        verbose_name = _("PAR")
        verbose_name_plural = _("PARs")

    def skill_count(self):
        return self.skills.count()

    def get_absolute_url(self):
        return reverse('par-detail', args=[str(self.id)])

    def __str__(self):
        return "{:03d} - {}".format(self.number + 1, self.name)


class Job(models.Model):
    """This model will list the core skills needed for a job"""

    name = models.CharField(max_length=200, verbose_name=_("Job"))
    core_skills = models.ManyToManyField(Skill, verbose_name=_("Core Skills"))

    class Meta:
        verbose_name = _("Job")
        verbose_name_plural = _("Jobs")

    def __str__(self):
        return "{}".format(self.name)

par/views.py
# from django.shortcuts import render
from django.views import generic
from .models import PAR, Skill


class IndexView(generic.ListView):
    template_name = 'par/index.html'

    def get_queryset(self):
        return PAR.objects.all()[:10]


class PARDetail(generic.DetailView):
    model = PAR


class SkillList(generic.ListView):
    model = Skill


class SkillDetail(generic.DetailView):
    model = Skill

par/templates/par/index.html
{% extends "base.html" %}

{% block pagetitle %}Liste der neuesten PARs{% endblock %}

{% block content %}
  <ul class="list-group mt-5">
    {% for object in object_list %}
    <li class="list-group-item">
      <a href="{{ object.get_absolute_url }}">
        {{ object.number|stringformat:"02d" }} &ndash; {{ object.name }}
        <small class="text-muted">({{ object.company }})</small>
      </a>
    </li>
    {% endfor %}
  </ul>
{% endblock content %}

<!-- vim:ts=2:sw=2:sts=2:syn=htmldjango
-->

par/templates/par/par_detail.html
{% extends "base.html" %}

{% block pagetitle %}
  {{ object.number|stringformat:"02d" }} &ndash; {{ object.name }}
{% endblock %}

{% block content %}
  <h2 class="text-muted">{{ object.company }}</h2>
  <div class="row">
    <div class="col-md-8">
      <div class="card my-4">
        <div class="card-header">
          <h5>Problem</h5>
        </div>
        <div class="card-body">
          <p class="card-text">
            {{ object.problem }}
          </p>
        </div>
      </div>
      <div class="card my-4">
        <div class="card-header">
          <h5>Aktion</h5>
        </div>
        <div class="card-body">
          <p class="card-text">
            {{ object.action }}
          </p>
        </div>
      </div>
      <div class="card my-4">
        <div class="card-header">
          <h5>Resultat</h5>
        </div>
        <div class="card-body">
          <p class="card-text">
            {{ object.result }}
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card my-4">
        <div class="card-header">
          <h5>Gezeigte Fähigkeiten</h5>
        </div>
        <ul class="list-group">
          {% for skill in object.skills.all %}
          <li class="list-group-item">
            <a href="{{ skill.get_absolute_url }}">{{ skill.name }}</a>
          </li>
          {% endfor %}
        </ul>
    </div>
  </div>
{% endblock content %}

<!-- vim:ts=2:sw=2:sts=2:syn=htmldjango
-->

par/templates/par/skill_detail.html
{% extends "base.html" %}

{% block pagetitle %}
  {{ object.name }}
{% endblock %}

{% block content %}
  <ul class="list-group mt-5">
    {% for par in object.par_set.all %}
    <li class="list-group-item">
    <a href="{{ par.get_absolute_url }}">
      {{ par.number|stringformat:"02d" }} &ndash; {{ par.name }}
      <small class="text-muted">({{ par.company }})</small>
    </a>
    </li>
    {% endfor %}
  </ul>
{% endblock content %}

<!-- vim:ts=2:sw=2:sts=2:syn=htmldjango
-->

par/templates/par/skill_list.html
{% extends "base.html" %}

{% block pagetitle %}Liste von Fähigkeiten{% endblock %}

{% block content %}
<table class="table table-striped table-bordered">
  <thead>
    <th>Fähigkeit</th>
    <th>Zugehörige PAR</th>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td>
        <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
      </td>
      <td>
        {% for par in object.par_set.all %}
          <a href="{{ par.get_absolute_url }}" class="mr-4">
            {{ par.number|stringformat:"02d" }}
          </a>
        {% endfor %}
      </td>
    </tr>
    {% endfor %}
  <tbody>
{% endblock content %}

<!-- vim:ts=2:sw=2:sts=2:syn=htmldjango
-->

templates/base.html
{% load static %}

<!doctype html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Outplacement Project">
    <meta name="author" content="Lutz Moppert">
    <title>Outplacement · PAR</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous">
  </head>
  <body>
    <nav id="header" class="navbar navbar-expand-md navbar-light bg-light border-bottom fixed-top" role="navigation">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/logo.png' %}" alt="Moppert" style="height: 35px;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNav" aria-controls="mainNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="mainNav">
          <ul class="navbar-nav mr-auto">
            {% block navlinks %} 
            <li class="nav-item homeLink mr-4" id="homeLink">
               <a href="/par" class="nav-link">
                 Startseite
               </a>
            </li>
            <li class="nav-item mr-4" id="skillLink">
               <a href="/par/skills" class="nav-link">
                 Fähigkeiten
               </a>
            </li>
            <li class="nav-item mr-4" id="adminLink">
              <a href="/admin" class="nav-link">
                Administration
              </a>
            </li>
            {% endblock navlinks %} 
          </ul>
        </div>
      </div>
    </nav>

    <main role="main" class="container" style="margin-top: 100px;">
      <h1 id="pagetile">
        {% block pagetitle %}
        Outplacement Application
        {% endblock pagetitle %}
      </h1>

      <div id="content">
        {% block content %}
        <p>Please navigate somewhere else</p>
        {% endblock content %}
      </div>
    </main>


    <!-- Javascript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/js/bootstrap.min.js"
      integrity="sha384-3qaqj0lc6sV/qpzrc1N5DC6i1VRn/HyX4qdPaiEFbn54VjQBEU341pvjz7Dv3n6P"
      crossorigin="anonymous">
    </script>
  </body>
</html>


<!-- vim:ts=2:sw=2:sts=2:syn=htmldjango
-->